### ISSUE TITLE
crash output (but did recover)

### ISSUE THREAD

**Issue by Mavmins** [NecronomiconCoding/NecroBot#105]
29 minutes crash, ptc login, but it did restart its self which was awesome. Just posting this in case it is in any way useful to track down the problem.

[00:30:38] (INFO) err: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<UpdatePlayerLocation>d__42.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 396
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__4.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Navigation.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__13.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__15.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 219
[00:30:39] (INFO) Awesome! You have already got the newest version! 1.0.2.2

**Comment by Arptastic** [comment]
I also have this problem anyway to fix this?

**Comment by Mavmins** [comment]
didnt recover from this but i was asleep so dont know if server related

[02:03:51] (ERROR) Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'pgorelease.nianticlabs.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__0`1.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPokemons>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__2.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<TransferDuplicatePokemon>d__18.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 430
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__13.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 343
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__15.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 254
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Console\Program.cs:line 22
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'pgorelease.nianticlabs.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__0`1.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI\Client.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPokemons>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__2.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<TransferDuplicatePokemon>d__18.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 430
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__13.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 343
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__15.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\pogo\BOT\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 254<---

**Comment by Mavmins** [comment]
hmmm it seems to be doing it an awful lot now, so random it was fine when i went to bed
