### ISSUE TITLE
[Error/v0.1.9] NullReferenceException

### ISSUE THREAD

**Issue by Sakaszli** [NecronomiconCoding/NecroBot#1056]
> (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchIncensePokemonsTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\CatchIncensePokemonsTask.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<>c__DisplayClass0_0.<<Execute>b__1>d.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Navigation.<HumanPathWalking>d__4.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Navigation.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43

It happens all the time, it's annoying ...

**Comment by Talamar1** [comment]
I'm getting it to, invalid path, the tvgfx doesn't exist on my system.  Someone hardcoded their test path in the code?

**Comment by Sparco2313** [comment]
This issue is caused by Pokémon spawned via incense, once your incene is gone the error won't occur anymore
