### ISSUE TITLE
Red text error?

### ISSUE THREAD

**Issue by mememaster161** [NecronomiconCoding/NecroBot#1061]
[17:31:32] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchIncensePokemonsTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\CatchIncensePokemonsTask.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass1_0.<<Execute>b__1>d.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Navigation.<HumanLikeWalking>d__3.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Navigation.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43

**Comment by mememaster161** [comment]
config file is this


{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "G:\\Downloads\\Release\\Release\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 52.379189,
  "DefaultLongitude": 4.899431,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 1000,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1000,
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "golduck",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": false,
  "ProfilePath": "G:\\Downloads\\Release\\Release",
  "RenameAboveIv": false,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251
}

**Comment by spot88** [comment]
Probably something wrong in config, delete it so it completes a new one.

**Comment by mememaster161** [comment]
that seems to have fixed it
