### ISSUE TITLE
GPX error please help

### ISSUE THREAD

**Issue by ayvasya** [NecronomiconCoding/NecroBot#1063]
```
[01:41:39] System.Xml.XmlException: Unexpected end tag. Line 194, position 9.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at PoGo.NecroBot.Logic.Utils.GpxReader..ctor(String xml, Context ctx) in C:\Users\ayvasya\Downloads\Compressed\NecroBot-master\PoGo.NecroBot.Logic\Utils\GPXReader.cs:line 43
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.GetGpxTracks(Context ctx) in C:\Users\ayvasya\Downloads\Compressed\NecroBot-master\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 143
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__0.MoveNext() in C:\Users\ayvasya\Downloads\Compressed\NecroBot-master\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ayvasya\Downloads\Compressed\NecroBot-master\PoGo.NecroBot.Logic\State\FarmState.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\ayvasya\Downloads\Compressed\NecroBot-master\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43
```

why i'am keep getting this when using gpx of my own? can someone explain me how to fix it? thanks..

**Comment by spot88** [comment]
I'm using dot, don't use comma. Probably that.

**Comment by ayvasya** [comment]
i'am using dot too  like  
  "DefaultLatitude": 42.389056,
  "DefaultLongitude": -71.135947,

**Comment by sloanja** [comment]
@ayvasya  Can you post your GPX file (use the Insert Code function) or put a link to a pastebin?

**Comment by jlrolin** [comment]
Run the XML through a validator.

**Comment by ayvasya** [comment]
```
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<trk><name>danehy</name><trkseg>
  <trkpt lat="42.38886911933985" lon="-71.13314867019653"></trkpt>
  <trkpt lat="42.38885327099469" lon="-71.13352417945862"></trkpt>
  <trkpt lat="42.38875818083966" lon="-71.13381385803223"></trkpt>
  <trkpt lat="42.38864724214339" lon="-71.13404989242554"></trkpt>
  <trkpt lat="42.38858384851464" lon="-71.13414645195007"></trkpt>
  <trkpt lat="42.38855215167624" lon="-71.13432884216309"></trkpt>
  <trkpt lat="42.388464985288145" lon="-71.13454341888428"></trkpt>
  <trkpt lat="42.38842536416266" lon="-71.1349081993103"></trkpt>
  <trkpt lat="42.38844121261586" lon="-71.13531589508057"></trkpt>
  <trkpt lat="42.38847290951027" lon="-71.13585233688354"></trkpt>
  <trkpt lat="42.38845706106506" lon="-71.13630294799805"></trkpt>
  <trkpt lat="42.388591772721725" lon="-71.13679647445679"></trkpt>
  <trkpt lat="42.38881365011428" lon="-71.1370861530304"></trkpt>
  <trkpt lat="42.38906722331683" lon="-71.13724708557129"></trkpt>
  <trkpt lat="42.38930494726395" lon="-71.13738656044006"></trkpt>
  <trkpt lat="42.389558518481856" lon="-71.13762259483337"></trkpt>
  <trkpt lat="42.38964568335142" lon="-71.13777279853821"></trkpt>
  <trkpt lat="42.38977246840018" lon="-71.1381483078003"></trkpt>
  <trkpt lat="42.389875481063726" lon="-71.13865256309509"></trkpt>
  <trkpt lat="42.38991510127393" lon="-71.13887786865234"></trkpt>
  <trkpt lat="42.38962983520231" lon="-71.13919973373413"></trkpt>
  <trkpt lat="42.38949512577341" lon="-71.13946795463562"></trkpt>
  <trkpt lat="42.38933664372221" lon="-71.1396074295044"></trkpt>
  <trkpt lat="42.38915438886863" lon="-71.13977909088135"></trkpt>
  <trkpt lat="42.38892458851643" lon="-71.14002585411072"></trkpt>
  <trkpt lat="42.38873440827838" lon="-71.1400043964386"></trkpt>
  <trkpt lat="42.38854422746414" lon="-71.13985419273376"></trkpt>
  <trkpt lat="42.38843328838977" lon="-71.13968253135681"></trkpt>
  <trkpt lat="42.38822725815999" lon="-71.13946795463562"></trkpt>
  <trkpt lat="42.388171788367224" lon="-71.1393392086029"></trkpt>
  <trkpt lat="42.38802915153214" lon="-71.13908171653748"></trkpt>
  <trkpt lat="42.388076697179834" lon="-71.13863110542297"></trkpt>
  <trkpt lat="42.388100469990185" lon="-71.13822340965271"></trkpt>
  <trkpt lat="42.38809254572107" lon="-71.13800883293152"></trkpt>
  <trkpt lat="42.387799347060536" lon="-71.1378800868988"></trkpt>
  <trkpt lat="42.38767255802642" lon="-71.1378264427185"></trkpt>
  <trkpt lat="42.387450676600544" lon="-71.13769769668579"></trkpt>
  <trkpt lat="42.38745860095068" lon="-71.1374831199646"></trkpt>
  <trkpt lat="42.387300113757775" lon="-71.13695740699768"></trkpt>
  <trkpt lat="42.386998986988836" lon="-71.1365818977356"></trkpt>
  <trkpt lat="42.38680880091685" lon="-71.1363136768341"></trkpt>
  <trkpt lat="42.38657899197777" lon="-71.13604545593262"></trkpt>
  <trkpt lat="42.38638880463337" lon="-71.13589525222778"></trkpt>
  <trkpt lat="42.386468049430235" lon="-71.13547682762146"></trkpt>
  <trkpt lat="42.38659484089714" lon="-71.13507986068726"></trkpt>
  <trkpt lat="42.386911818444034" lon="-71.1353051662445"></trkpt>
  <trkpt lat="42.38724464314571" lon="-71.13575577735901"></trkpt>
  <trkpt lat="42.38766463370329" lon="-71.13614201545715"></trkpt>
  <trkpt lat="42.38790236296219" lon="-71.1365282535553"></trkpt>
  <trkpt lat="42.388076697179834" lon="-71.13676428794861"></trkpt>
  <trkpt lat="42.38821140965278" lon="-71.13650679588318"></trkpt>
  <trkpt lat="42.38829065214887" lon="-71.13633513450623"></trkpt>
  <trkpt lat="42.38854422746414" lon="-71.13624930381775"></trkpt>
  <trkpt lat="42.38875818083966" lon="-71.1361312866211"></trkpt>
  <trkpt lat="42.38873440827838" lon="-71.13577723503113"></trkpt>
  <trkpt lat="42.388742332466485" lon="-71.13532662391663"></trkpt>
  <trkpt lat="42.38907514746292" lon="-71.13556265830994"></trkpt>
  <trkpt lat="42.38932079549507" lon="-71.1358630657196"></trkpt>
  <trkpt lat="42.389637759277385" lon="-71.13592743873596"></trkpt>
  <trkpt lat="42.389962645493156" lon="-71.13598108291626"></trkpt>
  <trkpt lat="42.3902558340493" lon="-71.13605618476868"></trkpt>
  <trkpt lat="42.39044600967778" lon="-71.13637804985046"></trkpt>
  <trkpt lat="42.39035092193555" lon="-71.13704323768616"></trkpt>
  <trkpt lat="42.390018113703405" lon="-71.13726854324341"></trkpt>
  <trkpt lat="42.39000226564834" lon="-71.13751530647278"></trkpt>
  <trkpt lat="42.39034299795055" lon="-71.13755822181702"></trkpt>
  <trkpt lat="42.39080258742815" lon="-71.13716125488281"></trkpt>
  <trkpt lat="42.39070750022612" lon="-71.13689303398132"></trkpt>
  <trkpt lat="42.390636184730056" lon="-71.13632440567017"></trkpt>
  <trkpt lat="42.39052524935291" lon="-71.1361312866211"></trkpt>
  <trkpt lat="42.3904143137797" lon="-71.1359167098999"></trkpt>
  <trkpt lat="42.39004980980156" lon="-71.13561630249023"></trkpt>
  <trkpt lat="42.38977246840018" lon="-71.13540172576904"></trkpt>
  <trkpt lat="42.38951889804657" lon="-71.13524079322815"></trkpt>
  <trkpt lat="42.38938418837956" lon="-71.13507986068726"></trkpt>
  <trkpt lat="42.38921778192119" lon="-71.13488674163818"></trkpt>
  <trkpt lat="42.38895628516675" lon="-71.1346185207367"></trkpt>
  <trkpt lat="42.388789877574" lon="-71.13441467285156"></trkpt>
  <trkpt lat="42.38851253060576" lon="-71.13402843475342"></trkpt>
  <trkpt lat="42.388464985288145" lon="-71.13382458686829"></trkpt>
  <trkpt lat="42.38837781877903" lon="-71.13354563713074"></trkpt>
  <trkpt lat="42.38821933390689" lon="-71.13341689109802"></trkpt>
  <trkpt lat="42.38805292436047" lon="-71.13336324691772"></trkpt>
  <trkpt lat="42.38794990870591" lon="-71.13328814506531"></trkpt>
  <trkpt lat="42.387854817182436" lon="-71.13325595855713"></trkpt>
  <trkpt lat="42.387720103944226" lon="-71.13347053527832"></trkpt>
  <trkpt lat="42.387680482348564" lon="-71.1335563659668"></trkpt>
  <trkpt lat="42.38750614703055" lon="-71.13383531570435"></trkpt>
  <trkpt lat="42.38739520612153" lon="-71.13407135009766"></trkpt>
  <trkpt lat="42.38731596249506" lon="-71.13429665565491"></trkpt>
  <trkpt lat="42.38721294563109" lon="-71.13458633422852"></trkpt>
  <trkpt lat="42.38714955055384" lon="-71.13483309745789"></trkpt>
  <trkpt lat="42.3872763406443" lon="-71.13514423370361"></trkpt>
  <trkpt lat="42.38764878505402" lon="-71.13565921783447"></trkpt>
  <trkpt lat="42.3878468928823" lon="-71.13583087921143"></trkpt>
  <trkpt lat="42.38805292436047" lon="-71.13609910011292"></trkpt>
  <trkpt lat="42.38842536416266" lon="-71.13661408424377"></trkpt>
  <trkpt lat="42.38848875795146" lon="-71.13689303398132"></trkpt>
  <trkpt lat="42.388575924306544" lon="-71.13736510276794"></trkpt>
  <trkpt lat="42.38860762113291" lon="-71.13778352737427"></trkpt>
  <trkpt lat="42.38869478732294" lon="-71.1381483078003"></trkpt>
  <trkpt lat="42.38878195339193" lon="-71.1385989189148"></trkpt>
  <trkpt lat="42.388980057643984" lon="-71.1389422416687"></trkpt>
  <trkpt lat="42.389241554299396" lon="-71.13881349563599"></trkpt>
  <trkpt lat="42.38938418837956" lon="-71.13822340965271"></trkpt>
  <trkpt lat="42.389415884797806" lon="-71.13776206970215"></trkpt>
  <trkpt lat="42.38965360742446" lon="-71.13698959350586"></trkpt>
  <trkpt lat="42.38965360742446" lon="-71.13662481307983"></trkpt>
  <trkpt lat="42.38929702314686" lon="-71.13635659217834"></trkpt>
  <trkpt lat="42.38890874018527" lon="-71.13588452339172"></trkpt>
  <trkpt lat="42.38854422746414" lon="-71.13553047180176"></trkpt>
  <trkpt lat="42.38821140965278" lon="-71.13505840301514"></trkpt>
  <trkpt lat="42.38798160584841" lon="-71.13424301147461"></trkpt>
  <trkpt lat="42.387490298341255" lon="-71.13378167152405"></trkpt>
  <trkpt lat="42.38703068461149" lon="-71.13348126411438"></trkpt>
  <trkpt lat="42.38666616098475" lon="-71.13320231437683"></trkpt>
  <trkpt lat="42.386483898377584" lon="-71.13313794136047"></trkpt>
  <trkpt lat="42.38627786174971" lon="-71.13328814506531"></trkpt>
  <trkpt lat="42.38611937157579" lon="-71.13330960273743"></trkpt>
  <trkpt lat="42.38571521982122" lon="-71.13270878791809"></trkpt>
  <trkpt lat="42.3855646528161" lon="-71.132333278656"></trkpt>
  <trkpt lat="42.38569144610759" lon="-71.13197922706604"></trkpt>
  <trkpt lat="42.38590540920632" lon="-71.13156080245972"></trkpt>
  <trkpt lat="42.386087673492995" lon="-71.13105654716492"></trkpt>
  <trkpt lat="42.38656314305441" lon="-71.13124966621399"></trkpt>
  <trkpt lat="42.38683257420734" lon="-71.13160371780396"></trkpt>
  <trkpt lat="42.38733181122835" lon="-71.13178610801697"></trkpt>
  <trkpt lat="42.38762501207263" lon="-71.13196849822998"></trkpt>
  <trkpt lat="42.388005378694764" lon="-71.13211870193481"></trkpt>
  <trkpt lat="42.38833027335941" lon="-71.13240838050842"></trkpt>
  <trkpt lat="42.388591772721725" lon="-71.1324942111969"></trkpt>
  <trkpt lat="42.38867596736035" lon="-71.13259345293045"></trkpt>
  <trkpt lat="42.38873440827838" lon="-71.13260015845299"></trkpt>
  <trkpt lat="42.38881662168115" lon="-71.1326014995575"></trkpt>
  <trkpt lat="42.38888793924455" lon="-71.1326202750206"></trkpt>
  <trkpt lat="42.388916664351356" lon="-71.13264307379723"></trkpt>
  <trkpt lat="42.38891765487204" lon="-71.1327114701271"></trkpt>
  <trkpt lat="42.38891567383065" lon="-71.13280802965164"></trkpt>
  <trkpt lat="42.38887209090413" lon="-71.13305881619453"></trkpt>
  <trkpt lat="42.38886416673243" lon="-71.13314732909203"></trkpt>
</trkseg></trk></gpx>


```

finally i found the problem thanks sloanja to remind me 

i just don't see this missing at the first  = <gpx creator="WTracks" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/1" version="1.1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
<trk><name>CPS</name><trkseg>

**Comment by Ilses** [comment]
Close the issue if it's working.
