### ISSUE TITLE
v0.1.9 error that prevents running, can anyone take a look please?

### ISSUE THREAD

**Issue by dbw-holic** [NecronomiconCoding/NecroBot#1120]
[14:09:07] 15x ItemPokeBall
[14:09:08] 12x ItemSuperPotion
[14:09:09] 50x ItemHyperPotion
[14:09:10] Incubator status update: 3.52km left
[14:09:10] System.IO.FileNotFoundException: Could not load file or assembly 'GeoCoordinatePortable, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'GeoCoordinatePortable, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.Execute(Context ctx, StateMachine machine)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by emoisback** [comment]
do you have GeoCoordinatePortable.dll in your bot folder?

**Comment by dbw-holic** [comment]
doesn't seem like, only have "GeoCoordinatePortable.pdb" and "GeoCoordinatePortable.xml".
I extracted from the latest v0.1.9 zip file, can I just use the file from previous release?

**Comment by dbw-holic** [comment]
Figured out. It must a unsuccessful extraction using 7zip. I re-downloaded the latest release, all files are there and it runs perfectly. Thank you for the help!
