### ISSUE TITLE
just started using it and this happens... anyone knows how to fix it ? 

### ISSUE THREAD

**Issue by kostaskyp** [NecronomiconCoding/NecroBot#1141]
[10:11:27] (UPDATE) Perfect! You already have the newest Version 0.1.9
[10:11:27] (INFO) Logging in using Google
[10:11:29] (ATTENTION) Opening Google Device page. Please paste the code using CTRL+V
[10:11:34] (ERROR) Couldnt copy to clipboard, do it manually
[10:11:34] (ERROR) Goto:  & enter

**Comment by 036** [comment]
Seems to be a bug with version 1.9.

**Comment by ProfessorPoke** [comment]
This has been posted multiple times. Look at open issues. There is something wrong with Google auth or the API they used to create the tokens. I have a copy of 1.0 that runs as long as I use my old token. The issue is with updated clients requesting a new token or a new person trying to set up the bot for the first time. If you have an old copy of your token you can use that.

**Comment by kostaskyp** [comment]
my bad for not looking previous threads but i am in a bit of a hurry , so , sorry ... Thanks for the quick reply .. ill just wait for the bug to get fixed!

**Comment by marcospic** [comment]
Hi,
At least you are getting there. When starting i am getting an error. Any workarround?

Unhandled exception: System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Clipboard.SetText(String text)
   at PokemonGo.RocketAPI.Login.GoogleLogin.<>c__DisplayClass6_0.<GetDeviceCode>b__0() in D:\vvvvv\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 63
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Press any key to continue . . .

**Comment by proesd** [comment]
#1117 #1150
