### ISSUE TITLE
【fix】no Google code or clipboard 

### ISSUE THREAD

**Issue by MythHack** [NecronomiconCoding/NecroBot#1146]

**Comment by NEtio789** [comment]
thank you... so, now where do I put this code?

**Comment by MythHack** [comment]
@NEtio789 I was just testing found that although he can generate a key, but the client does not seem to respond

**Comment by therealshibe** [comment]
Bummer I'm working on building a fix too.

**Comment by MythHack** [comment]
![image](https://cloud.githubusercontent.com/assets/7798759/17205347/33d1abc6-54dd-11e6-8996-3cc0e2c66870.png)

**Comment by kyza1** [comment]
what is the actual problem? not that I think i can contribute but I'm Nosey

**Comment by rohanmtkr** [comment]
Problem fixed??
no google code??

**Comment by KingHKS** [comment]
```
[16:08:18] Starting Execute on login server: Google
[16:08:19] Please visit  and enter
```
The link of www.google.com/device and the devices code is miss from now

**Comment by HZH1907** [comment]
same problem

[15:54:31] Logging in using Google
Initializing Rocket logger at time 2016-7-28 15:55:29...
[15:55:30] Failed to start WebSocketServer on port : 14251
[15:55:38] Perfect! You already have the newest Version 0.1.9
[15:55:38] Logging in using Google
[15:55:46] Opening Google Device page. Please paste the code using CTRL+V
[15:55:51] Couldnt copy to clipboard, do it manually
[15:55:51] Goto:  & enter 

Initializing Rocket logger at time 2016-7-28 16:04:45...
[16:04:46] Failed to start WebSocketServer on port : 14251
[16:05:28] Perfect! You already have the newest Version 0.1.9
[16:05:28] Logging in using Google
[16:06:44] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Unknown error (0x2751)
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.HttpClientHelper.<PostFormEncodedAsync>d__0`1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Helpers\HttpClientHelper.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__7.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__4.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43
[16:06:44] Logging in using Google

**Comment by Beneck** [comment]
yeah, same

**Comment by MythHack** [comment]
https://github.com/fahimsakri/pokemongo/blob/2581212218eca71f084512398cb9adad5f56c28f/app/google-services.json 
Here are a few google key

**Comment by rohanmtkr** [comment]
i have just download yesterday quick that time that shows mi code but today no code then i try to use all the bots which available on net but no code 
all bots r prompting same error no google code

**Comment by Nothingst** [comment]
@MythHack  how to fix it？

**Comment by rohanmtkr** [comment]
@MythHack  problem solved or not?

**Comment by GreatAnubis** [comment]
no, it's not. The google code is assigned to the account so we can't get some random one from someone else.

**Comment by GrunkyPeeps** [comment]
Yea, The Google Auth is down

**Comment by rohanmtkr** [comment]
really??

**Comment by GrunkyPeeps** [comment]
Yup

**Comment by GreatAnubis** [comment]
no it's not. It works for other apps.

**Comment by rohanmtkr** [comment]
guyz that bot still working for some people

**Comment by rohanmtkr** [comment]
and all google services are alive

**Comment by rohanmtkr** [comment]
except gmail

**Comment by MythHack** [comment]
@GreatAnubis But it is also a pokemon go confirmation page

**Comment by rohanmtkr** [comment]
any other way to sign in through bot?

**Comment by tienrocker** [comment]
![pkmgobot](https://cloud.githubusercontent.com/assets/1247389/17206575/a7eeb3c6-54da-11e6-8da7-d52209fb5329.png)
change your api config, work like a charm

**Comment by NEtio789** [comment]
can you pass the file fix it?

**Comment by rohanmtkr** [comment]
can u post that code so i can copy paste

**Comment by GrunkyPeeps** [comment]
yea

**Comment by rokuon** [comment]
would u upload the config folder sir? I have the refresh token but not the config or auth file

**Comment by DanFry** [comment]
Code can be found on the releases page -
https://github.com/NecronomiconCoding/NecroBot/releases

Visual Studio Download for compiling yourself - https://go.microsoft.com/fwlink/?LinkId=691978&clcid=0x409

however at the moment servers are down for Pokemon, see http://ispokemongodownornot.com/

could be an API update, a ban wave, a ddos or something else preventing the bots atm.

http://i.imgur.com/ONPpvEk.png
![image](https://cloud.githubusercontent.com/assets/3605392/17206898/e5dfda1a-54a9-11e6-99ef-2eb32ea822fc.png)

**Comment by cpasmoi** [comment]
hilarous

**Comment by rohanmtkr** [comment]
lol where is that msg who fix that problem

**Comment by rohanmtkr** [comment]
wht?
THe End?
Problem Fixed Or Not??

**Comment by eukaristia** [comment]
i think problem not fix
@MythHack  just create sensation lol
