### ISSUE TITLE
it keep 'Logging in using Google' with a red text

### ISSUE THREAD

**Issue by rizardhis** [NecronomiconCoding/NecroBot#1164]
i just happened a minutes ago, is there anyone experience this too ?

> [15:53:10] Logging in using Google
[15:53:10] System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at System.Net.Http.HttpClient.CreateUri(String uri)
   at System.Net.Http.HttpClient.PostAsync(String requestUri, HttpContent content)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<DownloadProfile>d__1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43

**Comment by BioMuell** [comment]
https://go.jooas.com/

**Comment by Shroomzie** [comment]
yeah its a major outage

**Comment by barr0ck** [comment]
It's happening to me aswell

**Comment by NielsVoorma** [comment]
I can login fine through bluestacks tho,

**Comment by adriantheplug** [comment]
Yeah bluestacks login is fine, but not the bot.

**Comment by chewbyte** [comment]
Can we panic yet?

**Comment by Triphase** [comment]
Error handling would be nice here. Detect the failure and build in a retry every X minutes (configurable via settings)

**Comment by H3RB4LS** [comment]
Logins down.
http://ispokemongodownornot.com/
http://ispokemongodownornot.com/
http://ispokemongodownornot.com/

**Comment by ducdigital** [comment]
Still can't login . Phone login is fine

**Comment by BSwazZ** [comment]
now is good

**Comment by pitisk** [comment]
(https://cloud.githubusercontent.com/assets/20699825/17207509/35c4fae6-54b5-11e6-8489-eb0bd39b98dd.png)

**Comment by themanwhocodes** [comment]
its working fine now

**Comment by ducdigital** [comment]
@all ok now. This issue can consider closed i guess

**Comment by Shroomzie** [comment]
Please close the issue. 200 issues. please stop posting issues over and over again.

**Comment by IDKas** [comment]
Still Can't login, :(

**Comment by rohanmtkr** [comment]
yea

**Comment by Shroomzie** [comment]
Its not a issue with this repos, Please stop posting your crap.

**Comment by rohanmtkr** [comment]
OMG Pokevision stops working now

**Comment by rohanmtkr** [comment]
Did pokemon go api changed?

**Comment by Triphase** [comment]
@Shroomzie My console gets flooded though. And is your phone that fast? Just saying, Error Handling should be there. Not saying that no errors should not be displayed, but you can catch the error and put a nice Error line there.
Also, making the option configurable gives a user the ability to make the bot more Human Like. Time the login/startup time of your phone and put that as a retry value.

**Comment by IDKas** [comment]
and than with phone can't login :))
