### ISSUE TITLE
[Guide] Fix Google Device Auth Issue *Outdated, working on fix*

### ISSUE THREAD

**Issue by Just2good** [NecronomiconCoding/NecroBot#1169]
*Important*
Does not work anymore, they switched to GPSOAuth, working on fix.

-Jinsoku

**Comment by Kalashnikitty** [comment]
Thank you very much.

**Comment by Eduardox** [comment]
@bjens39 check if this helps you

**Comment by Shroomzie** [comment]
This is not a issue. why on earth would you add to the 200+ scrub issues? You realise its not fun to go through these stupid posts? This is a guide and you should prolly push it to the wiki, not the issues...derp!!!!

**Comment by myo** [comment]
how safe is using your own oauth creds? weren't we using niantic before?

**Comment by myo** [comment]
it's easier to find here since everyone will complain about this issue @shroomzie

**Comment by hsizadam** [comment]
i cant change the lines

**Comment by artganify** [comment]
> i cant change the lines it says you must be on a brunch, what should i do

What? What exactly are you trying to do?

**Comment by myo** [comment]
@hsizadam download the repo as zip and change the lines on your computer
don't bother if you don't have/don't know what a compiler is though..

**Comment by Strike5221** [comment]
So I changed lines but do I have to put the file somewhere after because I start the file and still same thing.

**Comment by mpl1337** [comment]
not working for me

**Comment by Xalk444** [comment]
sorry that I can not compile  :-(

**Comment by bennextmitchell** [comment]
[10:47:46] (UPDATE) Perfect! You already have the newest Version 0.1.9
[10:47:46] (INFO) Logging in using Google
[10:47:47] (ATTENTION) Opening Google Device page. Please paste the code using CTRL+V
[10:48:07] (ERROR) PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException: Exception of type 'PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException' was thrown.
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__6.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__4.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\LoginState.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\StateMachine.cs:line 34
[10:48:07] (INFO) Logging in using Google
[10:48:38] (ERROR) PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException: Exception of type 'PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException' was thrown.
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__6.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__4.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\LoginState.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\StateMachine.cs:line 34
[10:48:44] (INFO) Logging in using Google
[10:48:44] (ERROR) PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException: Exception of type 'PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException' was thrown.
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__6.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__4.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\LoginState.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\StateMachine.cs:line 34
[10:48:44] (INFO) Logging in using Google

**Comment by artganify** [comment]
@hsizadam @Strike5221 

What you have to do is changing the SOURCE CODE of the application you first have to fetch via git or download as zip from the repo. Then after you made your changes you have to compile it either via msbuild or inside Visual Studio. If you don't know how to use git/github or C# compilation, you're really wrong here.

**Comment by mpl1337** [comment]
same :D

**Comment by hsizadam** [comment]
@myo yeah i am just a user dont know so much about this. i dont have a complier

**Comment by bennextmitchell** [comment]
okay, ima just wait untuil all is fixed :p

**Comment by mpl1337** [comment]
go out and play fair :D

**Comment by artganify** [comment]
@Just2good Can you close the issue? This is a noob magnet.

**Comment by guest136** [comment]
I followed your instructions exactly and get this now 

[11:50:38] (UPDATE) Perfect! You already have the newest Version 0.1.9
[11:50:38] (INFO) Logging in using Google
[11:50:39] (ATTENTION) Opening Google Device page. Please paste the code using CTRL+V
[11:50:44] (ERROR) Couldnt copy to clipboard, do it manually
[11:50:46] (ERROR) Goto:  & enter

**Comment by fee622** [comment]
me too

**Comment by myo** [comment]
if u have an old token it should work (used a 1 day old one)

**Comment by lotusJDM** [comment]
@myo But thats only if you're unlike most of us who tried to logon to another account and deleted your token while attempting to do so right lol

**Comment by lotusJDM** [comment]
Does anyone have the new discord chat invite?
