### ISSUE TITLE
Error While Executing PoGo.NecroBot.CLI.exe

### ISSUE THREAD

**Issue by salman102** [NecronomiconCoding/NecroBot#1182]
[13:22:17] (ERROR) Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at PokemonGo.RocketAPI.Helpers.JsonHelper.GetValue(String json, String key) in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Helpers\JsonHelper.cs:line 9
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__5.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43

**Comment by MadLluks** [comment]
Pls check server before post an issue ... 
http://ispokemongodownornot.com/

PTC login is down

**Comment by pacMakaveli** [comment]
Happens when you mess with the `config.json` file. It happened to me when I changed some values. I didn't bother debugging so I changed to defaults. I suggest you do the same and try and change one at a time see which line causes the issue.

**Comment by Aqua3** [comment]
Just extract the files from the zip into a new folder. It will refresh all the configs.

**Comment by Shroomzie** [comment]
Use sites like this to solve the issues. If you are not using a real IDE!

 http://json.parser.online.fr (put your config in it and it should tell you where the problems are.)
