### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by GWlodarek** [NecronomiconCoding/NecroBot#1239]
Release: 0.2.0

`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.CLI.LogicSettings.get_TranslationLanguageCode() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Settings.cs:line 464
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\Session.cs:line 33
   at PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.CLI\Program.cs:line 32`

Anyone else getting this?

Edit: This happens on the initial launch of the exe.
Edit 2: Seems to be fixed after running the exe again.

**Comment by bennextmitchell** [comment]
I'm getting a bunch of red text and loads of blue logging into google when I launch.

**Comment by bennextmitchell** [comment]
[16:12:29] (UPDATE) Perfect! You already have the newest Version 0.1.9
[16:12:29] (INFO) Logging in using Google
[16:12:29] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data)
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion)
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\Me\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 17
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__1.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\LoginState.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in C:\Users\Me\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\StateMachine.cs:line 34
[16:12:29] (INFO) Logging in using Google

and so on..

**Comment by GWlodarek** [comment]
@bennextmitchell have you tried 0.2.0? It just released.

**Comment by kittaru** [comment]
I have an issue with it parsing the username. Problem being it is not writing to the log.
![error](https://cloud.githubusercontent.com/assets/19661182/17218192/89b62a9e-5519-11e6-8d09-07ae2a515a7e.jpg)

**Comment by kittaru** [comment]
put username and password in "" if using google. Will accept the string then if you were getting errors.

**Comment by GWlodarek** [comment]
Fixed with the re-release of 0.2.0!

**Comment by bigwoodenspoon** [comment]
Still getting this error in v0.7.5.
