### ISSUE TITLE
Google Account have an issues !

### ISSUE THREAD

**Issue by KenzXander** [NecronomiconCoding/NecroBot#138]
`[10:21:54] (ERROR) Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.HttpClientHelper.<PostFormEncodedAsync>d__0`1.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI\Helpers\HttpClientHelper.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Login.GoogleLogin.<PollSubmittedToken>d__7.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__4.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI\Client.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI.Logic\Logic.cs:line 217
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI.Console\Program.cs:line 22
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.HttpClientHelper.<PostFormEncodedAsync>d__0`1.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI\Helpers\HttpClientHelper.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Login.GoogleLogin.<PollSubmittedToken>d__7.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__4.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI\Client.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in C:\Users\Windows 10\Desktop\New folder (6)\PokemonGo.RocketAPI.Logic\Logic.cs:line 217<---`
![image](https://cloud.githubusercontent.com/assets/20607191/17075520/c7f4d08e-50bf-11e6-9982-b423182317dc.png)
Please help me :(((((((((((((((((

**Comment by MichaelGatesDev** [comment]
It's failing to connect, possibly due to a firewall. That would be my guess. Run Visual Studio as administrator and disable your firewall/antivirus if you can.

**Comment by KenzXander** [comment]
:((( still not working

**Comment by Daylend** [comment]
Your bot is trying to connect to 127.0.0.1:443 for some reason. DNS issue?

**Comment by KenzXander** [comment]
sr but, can you explain for me :(
