### ISSUE TITLE
GetHighestPokemonOfTypeByCP throws Sequence contains no elements. Not thread safe

### ISSUE THREAD

**Issue by 5andr0** [NecronomiconCoding/NecroBot#144]
It seems to me (not a C# developer) that GetHighestPokemonOfTypeByCP is not thread safe because pokemons are removed from myPokemon during this loop `return pokemons.Where(x => x.PokemonId == pokemon.PokemonId)
                .OrderByDescending(x => x.Cp)
                .First();`

here's the error output (always happens after transfering, friend just reproduced that aswell):
`[06:45:56] (ERROR) Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable1 source)
   at PokemonGo.RocketAPI.Logic.Inventory.<GetHighestPokemonOfTypeByCP>d__5.MoveNext() in D:\games\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<TransferDuplicatePokemon>d__18.MoveNext() in D:\games\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 444
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__13.MoveNext() in D:\games\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 345
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__15.MoveNext() in D:\games\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 396
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__11.MoveNext() in D:\games\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 221
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in D:\games\Pokemon-Go-Bot\PokemonGo.RocketAPI.Console\Program.cs:line 22`

**Comment by dbfy** [comment]
Um, when he does ToList() on that IEnumerable<PokemonData>, I think he already copies the list. Therefore the original elements wouldn't matter because he's not directly referencing the original list. So if a pokemon was transferred, the array would resize, and make any logic requiring it throw an exception. I could be wrong.

**Comment by 5andr0** [comment]
FirstOrDefault seems to work so far. You can pull request/commit that
Thanks @dbfy

**Comment by dbfy** [comment]
Idk what pull or commit it lol, I don't even have visual studio installed.

**Comment by 5andr0** [comment]
https://github.com/NecronomiconCoding/Pokemon-Go-Bot/pull/139/commits/41503a28313a0f49964a4f9096e98c2be5b306ad

**Comment by dbfy** [comment]
tyvm
