### ISSUE TITLE
AutomaticallyLevelUpPokemon crashes

### ISSUE THREAD

**Issue by Lake292** [NecronomiconCoding/NecroBot#1554]
When you enable AutomaticallyLevelUpPokemon and the pokemon, which is supposed to be leveled up is at current max power up, due to trainer level, it will try to level it up anyway, which causes an exception with restart of the bot.

In game message, which grays out the power up button Trainer level is too low to power up.

Exception from the log, which is thrown immediately after starting the bot:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.LevelUpPokemonTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\LevelUpPokemonTask.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by NecronomiconCoding** [comment]
already adressed
