### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by abdellahaski** [NecronomiconCoding/NecroBot#1566]
Guys I'm getting this errors when ruining the bot

`ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

[19:14:06] (INFO) Logging in using Ptc
[19:14:07] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField
 called on an end-group tag, indicating that the corresponding start-group was m
issing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStrea
m input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.Move
Next() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\E
xtensions\HttpClientExtensions.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\t
vgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 4
4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\tvgfx
\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\tvgf
x\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

[19:14:07] (INFO) Logging in using Ptc
[19:14:07] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField
 called on an end-group tag, indicating that the corresponding start-group was m
issing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStrea
m input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.Move
Next() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\E
xtensions\HttpClientExtensions.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\t
vgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 4
4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\tvgfx
\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\tvgf
x\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

[19:14:07] (INFO) Logging in using Ptc
[19:14:08] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField
 called on an end-group tag, indicating that the corresponding start-group was m
issing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStrea
m input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.Move
Next() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\E
xtensions\HttpClientExtensions.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\t
vgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 4
4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\tvgfx
\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\tvgf
x\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

[19:14:08] (INFO) Logging in using Ptc
[19:14:08] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField
 called on an end-group tag, indicating that the corresponding start-group was m
issing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStrea
m input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.Move
Next() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\E
xtensions\HttpClientExtensions.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\t
vgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 4
4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\tvgfx
\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\tvgf
x\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

[19:14:08] (INFO) Logging in using Ptc
[19:14:09] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField
 called on an end-group tag, indicating that the corresponding start-group was m
issing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStrea
m input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.Move
Next() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\E
xtensions\HttpClientExtensions.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\t
vgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 4
4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\tvgfx
\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\tvgf
x\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

[19:14:09] (INFO) Logging in using Ptc
[19:14:09] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField
 called on an end-group tag, indicating that the corresponding start-group was m
issing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStrea
m input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.Move
Next() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\E
xtensions\HttpClientExtensions.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\t
vgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 4
4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\tvgfx
\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\tvgf
x\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

[19:14:09] (INFO) Logging in using Ptc
[19:14:10] (ERROR) Google.Protobuf.InvalidProtocolBufferException: SkipLastField
 called on an end-group tag, indicating that the corresponding start-group was m
issing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStrea
m input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.Move
Next() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\E
xtensions\HttpClientExtensions.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\t
vgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 4
4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\tvgfx
\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\tvgf
x\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

[19:14:10] (INFO) Logging in using Ptc
`

**Comment by abdellahaski** [comment]
I think it hasn't been resolved yet? I'm just trying to help
