### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Majesty01** [NecronomiconCoding/NecroBot#1738]
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\Desktop\Pokermon GO\0000\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 337

I keep getting many of these errors please fix

**Comment by bulubebek** [comment]
unstable internet connection? have you try to disable sniping?

**Comment by Sylencer90** [comment]
turn off snipe features?

**Comment by somani6** [comment]
turn off the 'Online' snipe feature. The Servers are busy right now.

**Comment by recon88** [comment]
Hey @Majesty01 
The Skiplagged API is currently having issues and answering slow.
https://skiplagged.com/pokemon/

There's nothing we can do about to except wait until they fix it.
