### ISSUE TITLE
Snipe function keep getting errors

### ISSUE THREAD

**Issue by qroneL** [NecronomiconCoding/NecroBot#1748]
Hi Guys,

I started to get errors while sniping, it seems some servers doesnt work stable, any idea to overcome this issue ?

Thanks.

[15:55:34] Scanning for Snipeable Pokemon at 40.712784,-74.005941...
[15:55:40] (CatchSuccess) | (Normal) Weedle Lvl: 18 CP: (182/230) IV: 36.00% | Chance: 35.29% | 8072042.24m dist | with a GreatBall (2 left). | Candies: 68
[15:55:42] Scanning for Snipeable Pokemon at 52.370216,4.895168...
[15:55:47] System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
[15:55:47] No Pokemon found to snipe!

**Comment by recon88** [comment]
The skiplagged servers are having a bad time. Therefore the bot doesn't get a response in time.
Just wait for them to fix it.
