### ISSUE TITLE
Error snipping ?

### ISSUE THREAD

**Issue by venomix** [NecronomiconCoding/NecroBot#1751]
[20:06:04] (SNIPER) No Pokemon found to snipe!
[20:06:04] (SNIPER) Scanning for Snipeable Pokemon at -33.86882,151.209296...
[20:06:09] (ERROR) System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346

**Comment by recon88** [comment]
The skiplagged API server is having a bad time and not responding in time.
Just wait for them to fix it.
