### ISSUE TITLE
Error while Sniping

### ISSUE THREAD

**Issue by SKULSHADY** [NecronomiconCoding/NecroBot#1782]
Hi guys I'm getting this error everytime
`[20:24:23] (SNIPER) Scanning for Snipeable Pokemon at -33.859019,151.213098...
 [20:24:28] (ERROR) System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location    location) in C:\Users\tvgfx\Documents\Pokemon Go  Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
  [20:24:35] (SNIPER) No Pokemon found to snipe!`

**Comment by nfettinger** [comment]
Have you asked for help in the Discord chat rooms yet (ask in room #helpme)?

"UseSnipeOnlineLocationServer": false,
"UseSnipeLocationServer": true,

This error has also been asked several times in open issues. Please do a search first next time before opening a new issue.

**Comment by recon88** [comment]
The API the bot is using is currently having a bad time. Please be patient.
