### ISSUE TITLE
Error on execution - Systemformatexception

### ISSUE THREAD

**Issue by saint-luciferr** [NecronomiconCoding/NecroBot#1797]
Hi,

I obtain the following error when executing the latest version

> [16:31:16] (ERROR) System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at PoGo.NecroBot.Logic.Common.Translation.GetTranslation(TranslationString translationString, Object[] data) in C:\Users\Agnute\Desktop\NecroBot-master #1\PoGo.Ne
croBot.Logic\Common\Translations.cs:line 356
   at PoGo.NecroBot.Logic.Tasks.GetPokeDexCount.<Execute>d__0.MoveNext() in C:\Users\Agnute\Desktop\NecroBot-master #1\PoGo.NecroBot.Logic\Tasks\GetPokeDexCount.cs:l
ine 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Agnute\Desktop\NecroBot-master #1\PoGo.NecroBot.Logic\State\FarmState.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Agnute\Desktop\NecroBot-master #1\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36`

Please advise?

Many thanks,

Lucifer`

**Comment by Oolaruu** [comment]
Which language do you use ?

**Comment by saint-luciferr** [comment]
English, the default version.

**Comment by recon88** [comment]
Could you please report that issue on our Discord's #helpme channel?
There will be someone assisting you: https://discord.gg/VXKxNFr
