### ISSUE TITLE
(ERROR) Unhandled exception

### ISSUE THREAD

**Issue by Lovebucket25** [NecronomiconCoding/NecroBot#202]
Keeps showing res text. 

[09:10:59] (ERROR) Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Requested value 'Blastiose' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at PokemonGo.RocketAPI.Console.Settings.LoadPokemonList(String filename) in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Console\Settings.cs:line 122
   at PokemonGo.RocketAPI.Console.Settings.get_PokemonsNotToTransfer() in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Console\Settings.cs:line 94
   at PokemonGo.RocketAPI.Logic.Logic.<TransferDuplicatePokemon>d__17.MoveNext() in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 459
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__14.MoveNext() in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 410
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 236
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Console\Program.cs:line 22
---> (Inner Exception #0) System.ArgumentException: Requested value 'Blastiose' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at PokemonGo.RocketAPI.Console.Settings.LoadPokemonList(String filename) in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Console\Settings.cs:line 122
   at PokemonGo.RocketAPI.Console.Settings.get_PokemonsNotToTransfer() in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Console\Settings.cs:line 94
   at PokemonGo.RocketAPI.Logic.Logic.<TransferDuplicatePokemon>d__17.MoveNext() in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 459
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__14.MoveNext() in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 410
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\FatKidsofAmerica\Desktop\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 236<---

**Comment by AdnanCukur** [comment]
Did you by any chance write Blastiose instead of Blastoise in one of the config files ?

**Comment by Lovebucket25** [comment]
I just downloaded the newest update to the Bot and have not edited anything except username, Pw, Lat:Lon

**Comment by AdnanCukur** [comment]
can you check the .txt files in the config folder if any of them contains "blastiose" ?

**Comment by Lovebucket25** [comment]
I found the Blastoise problem and fixed the typo, now it is having an issue with Alakazam

**Comment by Lovebucket25** [comment]
under PokemonGo.RocketAPI.console/Configs/ConfigPokemonsToKeep.txt
