### ISSUE TITLE
Crash: Unhandled exception.

### ISSUE THREAD

**Issue by Newkz** [NecronomiconCoding/NecroBot#223]
So from my Debug folder I have another copy of the compiled bot and put it in a folder in debug named PTC. Looks to me like it still tries to use the original Coords.txt file from the Debug folder and not the one in the PTC folder where this copy was running from.

[17:23:36] (POKESTOP) XP: 50, Gems: 0, Eggs:  Items: 1 x ItemPotion, 1 x ItemPokeBall, 1 x ItemUltraBall
[17:23:37] (TRANSFERED) Pidgey with 301 (48.61 % perfect) CP (Best: 494 | (65.88 % perfect))
[17:23:38] (TRANSFERED) Drowzee with 14 (67.77 % perfect) CP (Best: 784 | (75.13 % perfect))
[17:23:39] (ERROR) Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Console\bin\Debug\Coords.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at PokemonGo.RocketAPI.Client.SaveLatLng(Double lat, Double lng) in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI\Client.cs:line 313
   at PokemonGo.RocketAPI.Client.SetCoordinates(Double lat, Double lng, Double altitude) in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI\Client.cs:line 355
   at PokemonGo.RocketAPI.Client.<UpdatePlayerLocation>d__42.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI\Client.cs:line 400
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__3.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Navigation.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 336
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__14.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 407
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 264
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Console\Program.cs:line 22
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Console\bin\Debug\Coords.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at PokemonGo.RocketAPI.Client.SaveLatLng(Double lat, Double lng) in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI\Client.cs:line 313
   at PokemonGo.RocketAPI.Client.SetCoordinates(Double lat, Double lng, Double altitude) in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI\Client.cs:line 355
   at PokemonGo.RocketAPI.Client.<UpdatePlayerLocation>d__42.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI\Client.cs:line 400
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__3.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Navigation.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 336
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__14.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 407
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Newk\Desktop\Necronomicon PokeBot\PokemonGo.RocketAPI.Logic\Logic.cs:line 264<---

**Comment by Antidote78** [comment]
https://github.com/NecronomiconCoding/Pokemon-Go-Bot/issues/209

**Comment by Newkz** [comment]
@Antidote78 Doesn't seem related.
