### ISSUE TITLE
no clue why its going on 

### ISSUE THREAD

**Issue by cloudsstars** [NecronomiconCoding/NecroBot#310]
[17:24:20] (INFO) Awesome! You have already got the newest version! 1.0.4.0
[17:24:20] (ATTENTION) Make sure Lat & Lng is right. Exit Program if not! Lat: 40.768542406169 Lng: -73.9753537032322
[17:24:23] (INFO) Logging in via: Google
[17:24:24] (INFO) Google Device Code copied to clipboard

Unhandled Exception: System.Runtime.InteropServices.ExternalException: Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Clipboard.SetText(String text)
   at PokemonGo.RocketAPI.Login.GoogleLogin.<>c__DisplayClass6_0.<GetDeviceCode>b__0() in C:\Users\Clouds\Desktop\NecroBot-master\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 62
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Press any key to continue . . .

it gives me no code for this version and i dont know how to fix it all i did was update

**Comment by cloudsstars** [comment]
all i did was download and edit my settings for login and location

**Comment by Shroomzie** [comment]
ran it as admin yet? its trying to save the google key to clipboard so you can put it in the google site to get a auth

**Comment by cloudsstars** [comment]
closed
