### ISSUE TITLE
Error: the script no idea what

### ISSUE THREAD

**Issue by artsy23** [NecronomiconCoding/NecroBot#311]
[06:23:31] (ATTENTION) [#0 of 25] retry request https://pgorelease.nianticlabs.com/plfe/534/rpc - Error: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\lats\Desktop\NecroCom     Updated #2\NecroBot-master\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 30

**Comment by Hitsuomy** [comment]
Server related man, peak hour during weekend.

**Comment by cloudsstars** [comment]
ok thanks i was wondering why the old version still works but this one wont work. i will just go back to the last one it still works

**Comment by Hitsuomy** [comment]
Well, running with 4 accounts the newest compilation with no problems

**Comment by PureCS** [comment]
Consider closing the ticket if your issue is solved please.

**Comment by cloudsstars** [comment]
fixxed it had to go in to the error report click  Clipboard.SetText(deviceCode.user_code)); //Copy device code and it gave me a new code i entered it on the web page and now its working

**Comment by cloudsstars** [comment]
how do i do that @PureCS

**Comment by Shroomzie** [comment]
remember to close the issue if you find a solution

**Comment by PureCS** [comment]
@cloudsstars on this issue page scroll down and click `close issue`.
