### ISSUE TITLE
got this attention notice beetween catch

### ISSUE THREAD

**Issue by iamhahnz** [NecronomiconCoding/NecroBot#393]
[19:29:22] (POKESTOP) XP: 50, Gems: 0, Items: 1 x ItemRazzBerry, 1 x ItemGreatBall, 1 x ItemPokeBall, 1 x ItemSuperPotion
[19:29:28] (ATTENTION) [#0 of 25] retry request https://pgorelease.nianticlabs.com/plfe/409/rpc - Error: System.Net.Http.HttpReque
stException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'pg
orelease.nianticlabs.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in D:\poke\necromicon\penthiliawan\NecroBot-master\Pokem
onGo.RocketAPI\Helpers\RetryHandler.cs:line 30
[19:29:32] (TRANSFERED) Rattata with 37 (56,11 % perfect) CP (Best: 159 | (55,82 % perfect))
[19:29:32] (TRANSFERED) Rattata with 10 (53,04 % perfect) CP (Best: 159 | (55,82 % perfect))

**Comment by PureCS** [comment]
Server issues
