### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Potapy4** [NecronomiconCoding/NecroBot#444]
[20:17:53] (CatchSuccess) | Rattata Lvl 1 (10/10 CP) (9,00% perfect) | Chance: 100% | 81m dist | with a Normal ball.

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at PokemonGo.RocketAPI.Logic.Utils.Statistics.<_getcurrentLevelInfos>d__10.MoveNext() in C:\Users\Admin\Desktop\NecroBot-master\Poke
monGo.RocketAPI.Logic\Utils\Statistics.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Utils.Statistics.<UpdateConsoleTitle>d__21.MoveNext() in C:\Users\Admin\Desktop\NecroBot-master\Pokemon
Go.RocketAPI.Logic\Utils\Statistics.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserve
SyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by VirtualHeaven** [comment]
#430 same issue

**Comment by STEREOH** [comment]
Same here

**Comment by Ubuntoid** [comment]
replace line in PokemonGo.RocketAPI.Logic\Utils\Statistics.cs from
time = Convert.ToDouble(TimeSpan.FromHours(time).ToString("h\\.mm"))/100;

to
time = Convert.ToDouble(TimeSpan.FromHours(time).ToString("h\\,mm"))/100;
