### ISSUE TITLE
[ERROR] Downloaded from scratch, getting this ...

### ISSUE THREAD

**Issue by vcafezinho** [NecronomiconCoding/NecroBot#449]
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\...\Pokemon-Go-Bot-Necro\NecroBot\PokemonGo.RocketAPI.Console\bin\Debug\Logs\NecroBot-7\24\2016-12-32.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendText(String path)
   at PokemonGo.RocketAPI.Logger.Log(String message) in C:\...\Pokemon-Go-Bot-Necro\NecroBot\PokemonGo.RocketAPI\Logger.cs:line 50
   at PokemonGo.RocketAPI.Logger.SetLogger(ILogger logger) in C:\...\Pokemon-Go-Bot-Necro\NecroBot\PokemonGo.RocketAPI\Logger.cs:line 29
   at PokemonGo.RocketAPI.Console.Program.Main() in C:\...\Pokemon-Go-Bot-Necro\NecroBot\PokemonGo.RocketAPI.Console\Program.cs:line 16
Press any key to continue . . .

**Downloaded from scratch, getting this ...**

**Comment by TheIEnd** [comment]
I am also getting this on the latest commit

**Comment by kanfkasndklasdn** [comment]
The path have the date with \, nad it takes like a folder. I'm having the same error

**Comment by Potapy4** [comment]
it's seems like you don't have permission to write on current folder (maybe UAC blocked this). Try to start PokemonGo.RocketAPI.Console.exe via admin rigths

**Comment by vcafezinho** [comment]
Here is the deal, they have splitted in 2 branches, reverted lots of changes, those changes made all my files a mess, I decided to start from scratch and got this. About the Path "C:...\" i have just edited to not show my personal information about this. About "UAC" it is not possible, I am admin with all right, the files are in the same folder as before. UAC is disabled here.

**Comment by kanfkasndklasdn** [comment]
Are you sure it's not for the file name ("\")?

NecroBot-7\24\2016-12-32.txt
