### ISSUE TITLE
0.13 Division by 0 when evolving pokemon 

### ISSUE THREAD

**Issue by KurtCocain** [NecronomiconCoding/NecroBot#578]
Doesn't keep on going and do new stuff when out of pokemon to evolve. It just sits there waiting for pokemon to magically appear in inventory ^^

[08:18:04] Make sure Lat & Lng are right. Exit Program if not! Lat: 40.782353 Lng: -73.973874
[08:18:07] File: Configs\ConfigPokemonsToEvolve.ini not found, creating new...
[08:18:08] Pidgey successfully for 500xp
[08:18:11] Zubat successfully for 500xp
[08:18:14] Rattata successfully for 500xp
[08:18:17] File: Configs\ConfigPokemonsToKeep.ini not found, creating new...
[08:18:18] System.AggregateException: One or more errors occurred. ---> System.DivideByZeroException: Attempted to divide by zero.
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.Execute(Context ctx, StateMachine machine)
   at PoGo.NecroBot.Logic.State.FarmState.Execute(Context ctx, StateMachine machine)
   at PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context ctx)
---> (Inner Exception #0) System.DivideByZeroException: Attempted to divide by zero.
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__7.MoveNext()<---

[08:18:18] Playing as -------------
[08:18:18] Make sure Lat & Lng are right. Exit Program if not! Lat: 40.782353 Lng: -73.973874
[08:18:21] Failed Pidgey. EvolvePokemonOutProto.Result was FailedPokemonMissing, stopping evolving Pidgey
[08:18:24] Failed Zubat. EvolvePokemonOutProto.Result was FailedPokemonMissing, stopping evolving Zubat
[08:18:28] Failed Rattata. EvolvePokemonOutProto.Result was FailedPokemonMissing, stopping evolving Rattata
[08:18:31] System.AggregateException: One or more errors occurred. ---> System.DivideByZeroException: Attempted to divide by zero.
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.Execute(Context ctx, StateMachine machine)
   at PoGo.NecroBot.Logic.State.FarmState.Execute(Context ctx, StateMachine machine)
   at PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context ctx)
---> (Inner Exception #0) System.DivideByZeroException: Attempted to divide by zero.
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__7.MoveNext()<---

[08:18:31] Playing as -------------
[08:18:31] Make sure Lat & Lng are right. Exit Program if not! Lat: 40.782353 Lng: -73.973874
[08:18:35] System.AggregateException: One or more errors occurred. ---> System.DivideByZeroException: Attempted to divide by zero.
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.Execute(Context ctx, StateMachine machine)
   at PoGo.NecroBot.Logic.State.FarmState.Execute(Context ctx, StateMachine machine)
   at PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context ctx)
---> (Inner Exception #0) System.DivideByZeroException: Attempted to divide by zero.
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__7.MoveNext()<---

**Comment by yamashi** [comment]
This has been fixed for 0.1.4
