### ISSUE TITLE
Unhandled Exception: Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by spot88** [NecronomiconCoding/NecroBot#580]
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Line 20, position 20.
   at Newtonsoft.Json.JsonTextReader.ParseValue(Char currentChar)
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, Type t, JsonConverter propertyConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateAndPopulateObject(JsonReader reader, JsonObjectContract contract, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueNonProperty(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at PoGo.NecroBot.CLI.SettingsUtil.Load() in C:\Users\spot\Downloads\NecroBot-masterv2\PoGo.NecroBot.CLI\Settings.cs:line 41
   at PoGo.NecroBot.CLI.Program.Main() in C:\Users\**\Downloads\NecroBot-masterv2\PoGo.NecroBot.CLI\Program.cs:line 54

**Comment by yamashi** [comment]
Paste your config file.

**Comment by spot88** [comment]
{
  "AuthType": 1,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.76482,
  "DefaultLongitude": -73.97306,
  "DelayBetweenPokemonCatch": 5200,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "central-park.gpx",
  "KeepMinCp": 1000,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 85.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1100,
  "PrioritizeIvOverCp": false,
  "PtcPassword": "**",
  "PtcUsername": "***",
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": True,
  "UseLuckyEggsWhileEvolving": True,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 45.0
}

**Comment by yamashi** [comment]
Use v0.1.4

**Comment by spot88** [comment]
Then I get:
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Line 17, position 20.
   at Newtonsoft.Json.JsonTextReader.ParseValue(Char currentChar)
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, Type t, JsonConverter propertyConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateAndPopulateObject(JsonReader reader, JsonObjectContract contract, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueNonProperty(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PoGo.NecroBot.CLI.GlobalSettings.Load(String path) in D:\Dev\NecroBot\PoGo.NecroBot.CLI\Settings.cs:line 99
   at PoGo.NecroBot.CLI.Program.Main() in D:\Dev\NecroBot\PoGo.NecroBot.CLI\Program.cs:line 53

**Comment by spot88** [comment]
config.json ---- 
----------------

{
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.76482,
  "DefaultLongitude": -73.97306,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 1000,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 85.0,
  "KeepPokemonsThatCanEvolve": true,
  "MaxTravelDistanceInMeters": 1100,
  "PrioritizeIvOverCp": true,
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": True,
  "UseLuckyEggsWhileEvolving": True,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 45.0,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsToIgnore": [
    "zubat",
    "pidgey",
    "rattata"
  ],
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
    "mew",
    "mewtwo"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata"
  ]
}

**Comment by spot88** [comment]
Auth.json --
-------------

{
  "AuthType": "Ptc", (Tryed with 1 aswell).
  "GoogleRefreshToken": "",
  "PtcPassword": "*",
  "PtcUsername": "*"
}

**Comment by spot88** [comment]
@yamashi

**Comment by yamashi** [comment]
Use http://jsonlint.com/ to check your config files are correctly formated, this is not a bot issue.

**Comment by spot88** [comment]
Did that, and found out that it's casesensitive to "True\False" correct is : true\false. 
Get this now: 
' 
[15.02.01] System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException: Exception of type 'PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException' was thrown.
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__5.MoveNext() in D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 51
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PoGo.NecroBot.Logic.State.LoginState.Execute(Context ctx, StateMachine machine) in D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 17
   at PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context ctx) in D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 50
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException: Exception of type 'PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException' was thrown.
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__5.MoveNext() in D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 51<---
'

**Comment by spot88** [comment]
@yamashi

**Comment by yamashi** [comment]
Check your auth.json file... password and username are probably wrong
