### ISSUE TITLE
(ERROR) System.ArgumentOutOfRangeException:

### ISSUE THREAD

**Issue by spot88** [NecronomiconCoding/NecroBot#700]
System.ArgumentOutOfRangeException: The value of the parameter must be from -90.0 to 90.0.
Parameter name: Latitude
   at System.Device.Location.GeoCoordinate.set_Latitude(Double value)
   at System.Device.Location.GeoCoordinate..ctor(Double latitude, Double longitude, Double altitude, Double horizontalAccuracy, Double verticalAccuracy, Double speed, Double course)
   at System.Device.Location.GeoCoordinate..ctor(Double latitude, Double longitude)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in C:\Users\**\Downloads\NecroBot-master\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 17
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__0.MoveNext() in C:\Users\**\Downloads\NecroBot-master\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\**\Downloads\NecroBot-master\PoGo.NecroBot.Logic\State\FarmState.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\**\Downloads\NecroBot-master\PoGo.NecroBot.Logic\State\StateMachine.cs:line 44

-- config -- 
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 62.46494,
  "DefaultLongitude": 6.35084,

**Comment by spot88** [comment]
Turned off GPX pathing and worked. Has it changed so it uses . and not , in the .gpx file?

**Comment by spot88** [comment]
Yes it was the problem. Close please.
