### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xbtz** [NecronomiconCoding/NecroBot#717]
Whenever i try running the program, i get this error:

[08:23:21] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at PoGo.NecroBot.Logic.State.LoginState.Execute(Context ctx, StateMachine machine) in D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 26
   at PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context ctx) in D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 50

dont know really how to fix this, tried changing accounts but still not working

Thanks

**Comment by Kraker01** [comment]
Got this problem too. Reporting log:

`System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Errore del server remoto: (407) Richiesta autenticazione proxy.
   in System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   in System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)`

and more and more... How can I solve?

**Comment by ShawnHardwick** [comment]
`An existing connection was forcibly closed by the remote host` might indicate that the Pokemon Go servers are unstable or something happened with your internet connection.
