### ISSUE TITLE
[ERROR] System.NullReferenceException 

### ISSUE THREAD

**Issue by johnsilvavlogs** [NecronomiconCoding/NecroBot#747]
[21:15:11] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<>c__DisplayClass0_0.<Execute>b__0(PokemonSettings q) in C:\Users\John\Downloads\NecroBot-master (5)\NecroBot-master\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 88
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.Execute(Context ctx, StateMachine machine, Object encounter, MapPokemon pokemon, FortData currentFortData, UInt64 encounterId) in C:\Users\John\Downloads\NecroBot-master (5)\NecroBot-master\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 88
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.Execute(Context ctx, StateMachine machine, FortData currentFortData) in C:\Users\John\Downloads\NecroBot-master (5)\NecroBot-master\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 31
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.Execute(Context ctx, StateMachine machine) in C:\Users\John\Downloads\NecroBot-master (5)\NecroBot-master\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
   at PoGo.NecroBot.Logic.State.FarmState.Execute(Context ctx, StateMachine machine) in C:\Users\John\Downloads\NecroBot-master (5)\NecroBot-master\PoGo.NecroBot.Logic\State\FarmState.cs:line 35
   at PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context ctx) in C:\Users\John\Downloads\NecroBot-master (5)\NecroBot-master\PoGo.NecroBot.Logic\State\StateMachine.cs:line 50

**Comment by ShawnHardwick** [comment]
Please provide more details than that. Does it happen at the beginngin, during runtime? How long until it occurs?
