### ISSUE TITLE
There is something wrong

### ISSUE THREAD

**Issue by HZH1907** [NecronomiconCoding/NecroBot#757]
## I just follow all the steps, but it still show this. The vision  is v0.1.7. It's some file like GPXPath.PGX  disappear?

`[08:32:53] System.IO.FileNotFoundException: Could not find file 'C:\Program Files\Release\GPXPath.GPX'.
File name: 'C:\Program Files\Release\GPXPath.GPX'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.GetGpxTracks(Context ctx) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 137
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 44`

**Comment by Shroomzie** [comment]
Did you even read it? Its saying it cant find the file named GPXPath.GPX  in your folder. If you read the instructions you would know that turning that setting to "true" means you have to go and make a path on the website, save the file and either name it "GPXPath.GPX" or name it to whatever you like but also making sure you changed the name of the file its going to look for in the settings for the bot!! Its all in the wiki, so really there is little excuse for your derp.

If i was you i would slow down and try and understand what it is you are doing with code like this. Or you may get yourself into a world of trouble just willy nilly setting stuff to true and willy nilly downloading peoples code and running it on your computer.

**Comment by HZH1907** [comment]
@Shroomzie I'm sorry for I have done such a stupid thing. Thank you and I will try my best to change my idleness. Sorry again.
