### ISSUE TITLE
[ISSUE] PokemonGo.RocketAPI missing?

### ISSUE THREAD

**Issue by iBananaa** [NecronomiconCoding/NecroBot#892]
PokemonGo.RocketAPI folder is missing on github, so therefore it won't work?
https://gyazo.com/c0f7aac74b1ce12e06fbae8a94957e80

**Comment by bjwood** [comment]
If you pull with --recursive, you'll find the PokemonGo.RocketAPI folder is created from the linked FeroxRev repository. [Full instructions are here](https://github.com/NecronomiconCoding/NecroBot/wiki/Source-Code).

**Comment by PandaWalz** [comment]
It's done this way so that you are always downloading the most current PokemonGo.RocketAPI version.

Download it, take all the files and dump them in FeroxRev (In your NecroBot folder).

**Comment by iBananaa** [comment]
Thanks @bjwood @PandaWalz !

**Comment by PandaWalz** [comment]
NP, mark as closed if you are good.

**Comment by ManStache** [comment]
Is that what's causing this problem?

> Initializing Rocket logger at time 7/27/2016 6:19:47 AM...
[06:19:48] Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at PokemonGo.RocketAPI.Helpers.JsonHelper.GetValue(String json, String key) in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Helpers\JsonHelper.cs:line 9
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__5.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 44
Initializing Rocket logger at time 7/27/2016 6:20:02 AM...
Initializing Rocket logger at time 7/27/2016 6:20:13 AM...
Initializing Rocket logger at time 7/27/2016 6:22:26 AM...
