### ISSUE TITLE
2 bots banned after 2 hours farming

### ISSUE THREAD

**Issue by magikarpus** [NecronomiconCoding/NecroBot#900]
```
[15:57:31] (CatchSuccess) | (Normal) Weedle Lvl: 3 CP: (24/33) IV: 22,00% | Chance: 92,71% | 85,686316710883m dist | with a PokeBall (25 left). | Candies: {0}
[15:57:33] Looking for incense pokemon..
[15:57:37] Looking for pokemon..
[15:57:40] PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 29
```

Just change my location (one bot was in Russia, second in Japan) and start bot. Then wathching for two hours how them farming locations and suddenly them was banned. Accurate after 1h59m59sec

What is it?

Now accounts are banned\deleted (i cannot login at all)

**Comment by MikeLund** [comment]
What makes you think they are banned? I assume you're using PTC login, and PTC login server dies frequently.

**Comment by spot88** [comment]
PTC is down ATM

**Comment by spot88** [comment]
--close this

**Comment by magikarpus** [comment]
oh, rreaaly?
