### ISSUE TITLE
Got this error ( not sure what it means )

### ISSUE THREAD

**Issue by Tarnap95** [NecronomiconCoding/NecroBot#965]
[10:31:12] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exce
ption of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thro
wn.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0
`2.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.Rock
etAPI\Extensions\HttpClientExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in C:\
Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs
:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Player.<UpdatePlayerLocation>d__1.MoveNext() in C:
\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs
:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Navigation.<HumanLikeWalking>d__3.MoveNext() in C:\Use
rs\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Navigation.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:
\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTas
k.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\t
vgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\
tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43

**Comment by fossum** [comment]
Do you have a proxy? Or maybe a poor/intermittent connection?

**Comment by Tarnap95** [comment]
Wasn't using a proxy and I have never had problems with my net. Was running good for like half a hour and that happened

**Comment by knodel12** [comment]
This happened to me as well.  Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/20692379/17196461/658d5e16-542a-11e6-8bba-a2aff6008f34.png)

And the full text:
[18:40:51] (INFO) On The Wings of Angels 9/11 Memorial in (258m)
[18:41:33] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Map.<GetMapObjects>d__1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Map.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<GetNearbyPokemons>d__1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass1_0.<<Execute>b__1>d.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Navigation.<HumanLikeWalking>d__3.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Navigation.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43

**Comment by knodel12** [comment]
Not currently running a proxy.  Been running the bot for several hours and this just happened.  Doesn't seem to be stopping it, but it appeared to happen immediately after getting near a pokestop.

**Comment by Meigs2** [comment]
I'm having this issue as well after updating to 0.1.9... Was working on my machine at work earlier today.
